# Generated by Django 5.1.3 on 2025-05-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkincareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owned', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Limpiadores', 'Limpiadores'), ('Tonicos', 'Tónicos'), ('Serums', 'Serums'), ('Crema_hidratante', 'Crema hidratante'), ('Contorno_de_ojos', 'Contorno de ojos'), ('Exfoliantes', 'Exfoliantes'), ('Tratamiento_de_labios', 'Tratamiento de labios'), ('Desmaquillantes', 'Desmaquillantes'), ('Mascarillas', 'Mascarillas')], max_length=21)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='skincare_product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
